### ISSUE TITLE
piping final output to 'export-csv' gives undesired results

### ISSUE THREAD

**Issue by TheBigBear** [IISResetMe/PSProfiler#11]
@IISResetMe Hey, thanks for this great module, and I really enjoyed watching the Southhampton User Group call. Keep up all the good work. 

I have some 500 - 800 line scripts that currently run from anywhere between 3 to 6 hours if they complete at all. And for those bigger scripts, I think it would be really neat if I could relatively easily 'preserve' the output of the PSProfiler so I can keep coming back to it even days later and look at other sections to be improved upon. 

But maybe I was/am trying to do this the 'wrong' way? Whcih more than possible, even likley actually. Anyway if I run something like:

```Measure-Script -Path MyScript.ps1 | Tee-Object -Variable Measurements | Export-csv MyScript_psprofiler_output.csv```
then the output is:

```
"LineNo","ExecutionTime","TimeLine","Line","SourceScript"
"1","00:00:00","TimeLine","# test-psprofiler-1","C:temp\test-psprofiler-1.ps1"
```
Which is not all that useful for what I wanted.  
But what I would like to get out is, more something like: 

```
"Count"," Line","Time Taken","Statement"
5757,87,00:01.3884714,"$strdate = (Get-Date).ToString("dd MMMM yyyy")"
```

Am I doing it the 'wrong' way or can I 'massage' the output such that I get what I was looking for, or is it something you would have to add as a new feature in PSProfiler? And is it something you think others might find helpful to? 

Or maybe I just need to learn how to 'preserve' or save the contents of the array ```$Measurements``` that I did create. 

Hope this makes sense. Either way thanks again for this great module.

**Comment by IISResetMe** [comment]
Hey @TheBigBear!

You're not doing anything wrong, but you will need to "massage" the output a little bit to replicate the default format view:

```powershell
Measure-Script {
  Start-Sleep -Seconds 2
} |Select @{Name='Count';Expression={$_.TimeLine.GetCount()}},@{Name='Line';Expression='LineNo'},@{Name='Time Taken';Expression={$_.TimeLine.GetTotal()}},@{Name='Statement';Expression='Line'}
```

----

The reason PSProfiler defers this step to the formatting subsystems is simple: _preservation of underlying data points_ - allowing you to do more detailed analysis, useful for plotting the runtime complexity characteristics of the individual statement:

```
Measure-Script {
  $array = @()
  0..999 |ForEach-Object {
    $array += $_
  }
} |Select * -ExpandProperty TimeLine|Select * -ExpandProperty TimeSpans |Select LineNo,Ticks |Export-Csv .\detailedReport.csv 
```

Hope this helps!
