### ISSUE TITLE
Question: Why is the platform limited to amd64 ?

### ISSUE THREAD

**Issue by clowa** [IISResetMe/PSProfiler#14]
Hey everybody,
I was recently starting using your nice module to inspect my powershell script performance and figured out the module is limited to `amd64` processors.
```powershell
# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'Amd64'
```
However, I saved the module locally `Save-Module psprofiler -Path ~/modules/` and simply comment out the line above and `Measure-Script $PROFILE` also worked on `arm64`.

I tried to figure out which line of code limits the module to `amd64` but wasn't able to find anything.  
I'm quite new to powershell and wouldn't say I'm a good programmer, could you help me why this limitation is required? 

## Platform information
```powershell
PS /> $PSVersionTable
                                                                                                    
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by IISResetMe** [comment]
@clowa Excellent question! Target platform is specified as such because I've never _tested_ it on anything other than x86_64. 

To my best knowledge none of the APIs used are platform-sensitive, so it's entirely likely that it'll "just work" out of the box on ARM :-)

**Comment by clowa** [comment]
@IISResetMe, I really appreciate your quick reply!

I thought a bit about the reason for `ProcessorArchitecture` and if it is really intended for script modules. Since powershell core supports different processors/OS, any native powershell script built on powershell Core or dotnet core will run on all supported platforms, so I think it's more for binary modules compiled on a specific architecture. What do you think about my theory? I think it would be pretty cool to be able to use the module away from the classic Intel PCs. 🤔

**Comment by IISResetMe** [comment]
Binary modules are definitely the primary reason for the directive in the first place, but there are cases where it's relevant to script modules too:
 - Module has a dependency on an assembly of a certain bitness
 - Commands in module are designed to make platform-specific changes (eg. a function to disable SysWOW64 redirection in a 32-bit process on a 64-bit, only makes sense under x86 process)

**Comment by clowa** [comment]
@IISResetMe oh wow, I haven't thought about things so specific to processor architecture. Thanks for the explaination! Since my initinal question is already answered I' going to close this issue. Thanks again!
