### ISSUE TITLE
ScriptBlock is executed in module scope

### ISSUE THREAD

**Issue by nohwnd** [IISResetMe/PSProfiler#2]
https://github.com/IISResetMe/MeasureScript/blob/12100f386f7b673a540c929256355f9c111161bb/src/Public/Measure-Script.ps1#L91-L101

Processing the script block in the above way will detach it from the bound session state and invoke it in the module session state. This might result in unexpected behaviour, for example in this repro, the $variable is resolved to the value "module" instead to the expected "script". 

```powershell 

Get-Module -Name "m" | Remove-Module 
New-Module -Name "m" -ScriptBlock {
    $variable = "module"

    function Measure-ScriptStub {
        param ($ScriptBlock)
        $ScriptBlock = [scriptblock]::Create($ScriptBlock.ToString()) 
        # $profiler = [Profiler]::new($ScriptBlock.Ast.Extent) 
        # $visitor  = [AstVisitor]::new($profiler) 
        $newAst   = $ScriptBlock.Ast #.Visit($visitor) 
        
        if (-not $PSBoundParameters.ContainsKey('ExecutionResultVariable')){ 
            $null = & $newAst.GetScriptBlock() @Arguments 
        } 
        else { 
            $executionResult = . $newAst.GetScriptBlock() @Arguments 
        } 
    }
} | Import-Module

$variable = "script"
Measure-ScriptStub -ScriptBlock { Write-Host "-$variable-" }
```

The proposed solution is to save the inner session state and associate it back to the scriptblock after ast-rewrite. It is possible that more work will need to be done to communicate the state back to the measuring module, but that could be solved by exporting a utility function (in the most naive solution).

I can make a PR for this, if you think this issue is worth addressing.

**Comment by IISResetMe** [comment]
@nohwnd I believe the re-binding of `sessionStateInternal` addresses you concern, otherwise open a new issue :-)
