### ISSUE TITLE
The content of the 'count' property is false

### ISSUE THREAD

**Issue by LaurentDardenne** [IISResetMe/PSProfiler#6]
With psprofiler v1.0.2.0  , PS v5.1 Windows 10

```Powershell
Measure-Script {
   $t=dir c:\windows
   $h=@{}
   Write-warning "Count=$($t.count)"
   $t.name|foreach-object {$h.$_=$Name}
   $h=@{}
   $t|foreach-object {$h.$($t.Name)=$t.Name}
}
```
Result :
```Powershell
AVERTISSEMENT : Count=111

    Anonymous ScriptBlock

      Count  Line       Time Taken Statement
      -----  ----       ---------- ---------
          0     1    00:00.0000000 {
          1     2    00:00.0067198    $t=dir c:\windows
          1     3    00:00.0017389    $h=@{}
          1     4    00:00.0082062    Write-warning "Count=$($t.count)"
        112     5    00:00.3054616    $t.name|foreach-object {$h.$_=$Name}
          1     6    00:00.0016637    $h=@{}
        223     7    00:00.3768949    $t|foreach-object {$h.$($t.Name)=$t.Name}
          0     8    00:00.0000000 }
```
The count for the second foreach is false or ambiguous.

**Comment by IISResetMe** [comment]
Hey @LaurentDardenne!

This is actually working-as-designed - the count of `112` on line 5 accounts for:
 - 1 execution of the expression `$t.name | Foreach-Object { ... }`
 - 111 executions of the expression `$h.$_=$name`

The count of `223` on line 7 accounts for:
 - 1 execution of the expression `$t | Foreach-Object { ... }`
 - 111 executions of the expression `$h.$(...)=$t.$name`
 - 111 executions of the subexpression `$($t.$name)`

Unfortunately, right now there's no easy way to distinguish between which statement of expressions (starting on the same line) is "counting". 

For a v2 release I'll be working on tagging each execution so they can be tied back to the nodes in the AST, but as a v1 workaround, you can re-format your scripts to emit more granular timing information:

```
$t.name|foreach-object {
    $h.$_=$Name
}
# vs
$t.name|foreach-object {$h.$_=$Name}
```

This obviously warrants better documentation, I've opened #9 for this!

**Comment by LaurentDardenne** [comment]
I understand.
I had a doubt about this behavior with this instruction:
```powershell
$t|foreach-object {$h.$($t.Name) = $t.Name}
```

> For a v2 release I'll be working on tagging each execution so they can be tied back to the nodes in the AST

Perhaps the number of instructions in the result is missing?
Verbose mode or deep analysis mode would be appreciated.
A first reading without too much detail makes it possible to indicate the blocks to be optimized.
